from __future__ import annotations

# Один файл для чисел баланса.
# Если что-то выглядит плохо, сначала правим здесь, а не ищем магические числа по проекту.

CAMPAIGN_MAX_WAVES = 10
FINAL_BOSS_WAVE = CAMPAIGN_MAX_WAVES + 1

# Анимации и спрайты
ENEMY_FRAME_SIZE = 48
ENEMY_FRAMES_PER_ROW = 6
ENEMY_DIRECTION_ROWS = {
    "up": 0,
    "down": 1,
    "left": 2,
    "right": 3,
}
ENEMY_SPRITE_PADDING = 4
ENEMY_SPRITE_BASELINE_PADDING = 3
ENEMY_TARGET_DRAW_SIZE = 40
BOSS_TARGET_DRAW_SIZE = 48

# HP bar
HEALTH_BAR_WIDTH = 42
HEALTH_BAR_HEIGHT = 8
HEALTH_BAR_INNER_PADDING = 2
HEALTH_BAR_OFFSET_Y = 33
HEALTH_BAR_BORDER_COLOR = (245, 237, 211)
HEALTH_BAR_OUTLINE_COLOR = (34, 18, 25)
HEALTH_BAR_BACKGROUND_COLOR = (56, 25, 34)
HEALTH_BAR_FILL_COLOR = (78, 205, 91)
HEALTH_BAR_LOW_FILL_COLOR = (224, 72, 62)

# Тень под врагом
ENEMY_SHADOW_COLOR = (20, 18, 22, 95)
ENEMY_SHADOW_WIDTH = 32
ENEMY_SHADOW_HEIGHT = 10
BOSS_SHADOW_WIDTH = 42
BOSS_SHADOW_HEIGHT = 13
SHADOW_OFFSET_Y = 15

# Движение
EPSILON = 0.0001
MIN_ENEMY_PATH_GAP = 30.0
MIN_ENEMY_SPAWN_GAP = 34.0
LANE_OFFSETS = (-10.0, 0.0, 10.0)
LANE_SWITCH_SPEED = 42.0

# Волны
GOAL_ATTACK_DURATION = 0.35
DEATH_ANIMATION_DURATION = 0.55
MIN_SPAWN_INTERVAL = 0.25
MAX_ACTIVE_ENEMIES = 30
MAX_ENDLESS_SPEED_MULTIPLIER = 1.80

# Бесконечный режим — пока только настройки-почва.
ENDLESS_START_WAVE = 1
ENDLESS_BOSS_EVERY = 5
ENDLESS_MAX_ACTIVE_ENEMIES = 35
